### ISSUE TITLE
How to build from source

### ISSUE THREAD

**Issue by anildadj** [aquaskyline/SOAP3-dp#5]
Hi,

My system has 64GB of RAM and 4GB GDDR5 M1200 Nvidia GPU.

Please help resolve and run the program.
I am trying to do "make" from inside the downloaded master folder. 

But it gives error like - 

`SOAP3-DP.o: In function `main':
.SOAP3-DP.cpp:(.text.startup+0x1899): undefined reference to `gzclose'
.SOAP3-DP.cpp:(.text.startup+0x18b4): undefined reference to `gzclose'
.SOAP3-DP.cpp:(.text.startup+0x22b5): undefined reference to `gzopen'
.SOAP3-DP.cpp:(.text.startup+0x22e0): undefined reference to `gzread'
.SOAP3-DP.cpp:(.text.startup+0x2327): undefined reference to `gzopen'
.SOAP3-DP.cpp:(.text.startup+0x2352): undefined reference to `gzread'
.SOAP3-DP.cpp:(.text.startup+0x2382): undefined reference to `gzopen'
.SOAP3-DP.cpp:(.text.startup+0x23b5): undefined reference to `gzread'
.SOAP3-DP.cpp:(.text.startup+0x2418): undefined reference to `gzopen'
.SOAP3-DP.cpp:(.text.startup+0x2443): undefined reference to `gzread'
.SOAP3-DP.cpp:(.text.startup+0x2658): undefined reference to `gzeof'
.SOAP3-DP.cpp:(.text.startup+0x2675): undefined reference to `gzerror'
.SOAP3-DP.cpp:(.text.startup+0x28d5): undefined reference to `gzeof'
.SOAP3-DP.cpp:(.text.startup+0x28f2): undefined reference to `gzerror'
QueryParser.o: In function `loadPairReadsGz2(gzFile_s*, char*, gzFile_s*, char*, unsigned char*, unsigned int*, unsigned int*, unsigned int*, char*, char*, unsigned int, unsigned int, unsigned long&, char&, unsigned int&, unsigned long&, char&, unsigned int&, unsigned int, unsigned int, int, char&, int)':
QueryParser.cpp:(.text+0x14a0): undefined reference to `gzread'
QueryParser.cpp:(.text+0x15d2): undefined reference to `gzread'
QueryParser.cpp:(.text+0x175e): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x1776): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x17ee): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x181e): undefined reference to `gzread'
QueryParser.cpp:(.text+0x1856): undefined reference to `gzread'
QueryParser.cpp:(.text+0x186b): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x18ce): undefined reference to `gzread'
QueryParser.cpp:(.text+0x18fe): undefined reference to `gzread'
QueryParser.cpp:(.text+0x192e): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x1b1a): undefined reference to `gzread'
QueryParser.cpp:(.text+0x1b85): undefined reference to `gzread'
QueryParser.cpp:(.text+0x1bb6): undefined reference to `gzread'
QueryParser.cpp:(.text+0x1bee): undefined reference to `gzread'
QueryParser.cpp:(.text+0x1c26): undefined reference to `gzread'
QueryParser.o:QueryParser.cpp:(.text+0x1cce): more undefined references to `gzread' follow
QueryParser.o: In function `loadPairReadsGz2(gzFile_s*, char*, gzFile_s*, char*, unsigned char*, unsigned int*, unsigned int*, unsigned int*, char*, char*, unsigned int, unsigned int, unsigned long&, char&, unsigned int&, unsigned long&, char&, unsigned int&, unsigned int, unsigned int, int, char&, int)':
QueryParser.cpp:(.text+0x1d19): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x1d33): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x1d5e): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x1d7e): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x1d9e): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x1db8): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x1dd2): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x1df6): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x1e10): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x1e36): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x1e50): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x1e76): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x1e90): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x1eb6): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x1ee0): undefined reference to `gzread'
QueryParser.cpp:(.text+0x1f1b): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x1f3e): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x1f58): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x1f86): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x1fae): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x1fe3): undefined reference to `gzread'
QueryParser.cpp:(.text+0x2188): undefined reference to `gzread'
QueryParser.cpp:(.text+0x22c6): undefined reference to `gzread'
QueryParser.cpp:(.text+0x23fe): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x241e): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x2496): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x24be): undefined reference to `gzread'
QueryParser.cpp:(.text+0x24f7): undefined reference to `gzread'
QueryParser.cpp:(.text+0x250d): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x256a): undefined reference to `gzread'
QueryParser.cpp:(.text+0x2582): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x2598): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x25c6): undefined reference to `gzread'
QueryParser.cpp:(.text+0x25fe): undefined reference to `gzread'
QueryParser.cpp:(.text+0x2636): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x2860): undefined reference to `gzread'
QueryParser.cpp:(.text+0x28d2): undefined reference to `gzread'
QueryParser.cpp:(.text+0x2906): undefined reference to `gzread'
QueryParser.cpp:(.text+0x293e): undefined reference to `gzread'
QueryParser.cpp:(.text+0x297e): undefined reference to `gzread'
QueryParser.o:QueryParser.cpp:(.text+0x29da): more undefined references to `gzread' follow
QueryParser.o: In function `loadPairReadsGz2(gzFile_s*, char*, gzFile_s*, char*, unsigned char*, unsigned int*, unsigned int*, unsigned int*, char*, char*, unsigned int, unsigned int, unsigned long&, char&, unsigned int&, unsigned long&, char&, unsigned int&, unsigned int, unsigned int, int, char&, int)':
QueryParser.cpp:(.text+0x2a03): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x2a1e): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x2a39): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x2a54): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x2a6e): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x2a96): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x2ab0): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x2ad6): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x2af0): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x2b16): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x2b30): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x2b66): undefined reference to `gzread'
QueryParser.cpp:(.text+0x2b9c): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x2bbf): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x2bee): undefined reference to `gzread'
QueryParser.cpp:(.text+0x2c3f): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x2c6e): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x2c9e): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x2cc6): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x2ce0): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x2d0e): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x2d37): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x2d59): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x2d86): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x2da0): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x2dce): undefined reference to `gzread'
QueryParser.cpp:(.text+0x2e0a): undefined reference to `gzread'
QueryParser.cpp:(.text+0x2e47): undefined reference to `gzread'
QueryParser.cpp:(.text+0x2e7d): undefined reference to `gzread'
QueryParser.cpp:(.text+0x2eb0): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x2edd): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x2eff): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x2f56): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x2f76): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x2f9d): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x2fb7): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x2fd6): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x2ff0): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x3023): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x3058): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x3086): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x30a0): undefined reference to `gzerror'
QueryParser.o: In function `loadSingleReadsGz(gzFile_s*, char*, unsigned char*, unsigned int*, unsigned int*, unsigned int*, char*, char*, unsigned int, unsigned int, unsigned long&, char&, unsigned int&, unsigned int, unsigned int, int, char&, int)':
QueryParser.cpp:(.text+0x32be): undefined reference to `gzread'
QueryParser.cpp:(.text+0x33f3): undefined reference to `gzread'
QueryParser.cpp:(.text+0x3545): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x3565): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x35e2): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x360d): undefined reference to `gzread'
QueryParser.cpp:(.text+0x3645): undefined reference to `gzread'
QueryParser.cpp:(.text+0x365b): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x36c5): undefined reference to `gzread'
QueryParser.cpp:(.text+0x36fd): undefined reference to `gzread'
QueryParser.cpp:(.text+0x372a): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x3904): undefined reference to `gzread'
QueryParser.cpp:(.text+0x396c): undefined reference to `gzread'
QueryParser.cpp:(.text+0x399d): undefined reference to `gzread'
QueryParser.cpp:(.text+0x39d5): undefined reference to `gzread'
QueryParser.cpp:(.text+0x3a0d): undefined reference to `gzread'
QueryParser.o:QueryParser.cpp:(.text+0x3aad): more undefined references to `gzread' follow
QueryParser.o: In function `loadSingleReadsGz(gzFile_s*, char*, unsigned char*, unsigned int*, unsigned int*, unsigned int*, char*, char*, unsigned int, unsigned int, unsigned long&, char&, unsigned int&, unsigned int, unsigned int, int, char&, int)':
QueryParser.cpp:(.text+0x3af8): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x3b0e): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x3b35): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x3b55): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x3b75): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x3b8f): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x3ba5): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x3bc5): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x3bdb): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x3bfd): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x3c13): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x3c35): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x3c4b): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x3c6d): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x3c94): undefined reference to `gzread'
QueryParser.cpp:(.text+0x3cc9): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x3cf2): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x3d15): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x3d2b): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x3d52): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x3d7d): undefined reference to `gzread'
QueryParser.cpp:(.text+0x3da8): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x3dca): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x3de5): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x3e05): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x3e17): undefined reference to `gzerror'
QueryParser.cpp:(.text+0x3e65): undefined reference to `gzread'
QueryParser.cpp:(.text+0x3e8c): undefined reference to `gzeof'
QueryParser.cpp:(.text+0x3e9e): undefined reference to `gzerror'
samtools-0.1.18/bgzf.o: In function `deflate_block(BGZF*, int)':
bgzf.c:(.text+0xad): undefined reference to `deflateInit2_'
bgzf.c:(.text+0xc5): undefined reference to `deflate'
bgzf.c:(.text+0xda): undefined reference to `deflateEnd'
bgzf.c:(.text+0x152): undefined reference to `deflateInit2_'
bgzf.c:(.text+0x16b): undefined reference to `deflate'
bgzf.c:(.text+0x180): undefined reference to `deflateEnd'
bgzf.c:(.text+0x1d8): undefined reference to `deflateInit2_'
bgzf.c:(.text+0x1f0): undefined reference to `deflate'
bgzf.c:(.text+0x205): undefined reference to `deflateEnd'
bgzf.c:(.text+0x27a): undefined reference to `deflateInit2_'
bgzf.c:(.text+0x28d): undefined reference to `deflate'
bgzf.c:(.text+0x29e): undefined reference to `deflateEnd'
bgzf.c:(.text+0x314): undefined reference to `deflateEnd'
bgzf.c:(.text+0x352): undefined reference to `crc32'
bgzf.c:(.text+0x360): undefined reference to `crc32'
samtools-0.1.18/bgzf.o: In function `bgzf_read_block':
bgzf.c:(.text+0xacc): undefined reference to `inflateInit2_'
bgzf.c:(.text+0xae1): undefined reference to `inflate'
bgzf.c:(.text+0xaf2): undefined reference to `inflateEnd'
bgzf.c:(.text+0x143a): undefined reference to `inflateEnd'
samtools-0.1.18/bgzf.o: In function `bgzf_close':
bgzf.c:(.text+0x19bc): undefined reference to `deflateInit2_'
bgzf.c:(.text+0x19d3): undefined reference to `deflate'
bgzf.c:(.text+0x19e6): undefined reference to `deflateEnd'
bgzf.c:(.text+0x1b19): undefined reference to `deflateEnd'
bgzf.c:(.text+0x1b4e): undefined reference to `crc32'
bgzf.c:(.text+0x1b5b): undefined reference to `crc32'
samtools-0.1.18/bam_import.o: In function `ks_getuntil2(__kstream_t*, int, __kstring_t*, int*, int) [clone .constprop.6]':
bam_import.c:(.text+0x9b): undefined reference to `gzread'
samtools-0.1.18/bam_import.o: In function `__bam_get_lines(char const*, int*)':
bam_import.c:(.text+0x3aa): undefined reference to `gzdopen'
bam_import.c:(.text+0x47c): undefined reference to `gzread'
bam_import.c:(.text+0x8ad): undefined reference to `gzclose'
bam_import.c:(.text+0x915): undefined reference to `gzopen'
samtools-0.1.18/bam_import.o: In function `sam_header_read2':
bam_import.c:(.text+0x97f): undefined reference to `gzdopen'
bam_import.c:(.text+0xa3a): undefined reference to `gzread'
bam_import.c:(.text+0xd3a): undefined reference to `gzread'
bam_import.c:(.text+0x13a3): undefined reference to `gzread'
bam_import.c:(.text+0x1466): undefined reference to `gzclose'
bam_import.c:(.text+0x195c): undefined reference to `gzopen'
samtools-0.1.18/bam_import.o: In function `sam_header_read':
bam_import.c:(.text+0x209b): undefined reference to `gzread'
bam_import.c:(.text+0x23e6): undefined reference to `gzread'
samtools-0.1.18/bam_import.o: In function `sam_read1':
bam_import.c:(.text+0x3238): undefined reference to `gzread'
samtools-0.1.18/bam_import.o: In function `sam_open':
bam_import.c:(.text+0x4317): undefined reference to `gzdopen'
bam_import.c:(.text+0x438b): undefined reference to `gzopen'
samtools-0.1.18/bam_import.o: In function `sam_close':
bam_import.c:(.text+0x43cc): undefined reference to `gzclose'
samtools-0.1.18/razf.o: In function `razf_open_w(int)':
razf.c:(.text+0x89): undefined reference to `deflateInit2_'
razf.c:(.text+0x116): undefined reference to `deflateSetHeader'
samtools-0.1.18/razf.o: In function `razf_open_r(int, int)':
razf.c:(.text+0x62b): undefined reference to `inflateInit2_'
razf.c:(.text+0x6e5): undefined reference to `inflateEnd'
samtools-0.1.18/razf.o: In function `razf_write':
razf.c:(.text+0xcef): undefined reference to `deflate'
razf.c:(.text+0xf90): undefined reference to `deflate'
razf.c:(.text+0x12bf): undefined reference to `deflate'
razf.c:(.text+0x1381): undefined reference to `deflate'
samtools-0.1.18/razf.o: In function `razf_read':
razf.c:(.text+0x1a0d): undefined reference to `inflate'
samtools-0.1.18/razf.o: In function `razf_skip(RandomAccessZFile*, int)':
razf.c:(.text+0x1f74): undefined reference to `inflate'
samtools-0.1.18/razf.o: In function `razf_jump(RandomAccessZFile*, long, int)':
razf.c:(.text+0x21cc): undefined reference to `inflateReset'
samtools-0.1.18/razf.o: In function `razf_seek':
razf.c:(.text+0x23f4): undefined reference to `inflateReset'
samtools-0.1.18/razf.o: In function `razf_seek2':
razf.c:(.text+0x24b9): undefined reference to `inflateReset'
samtools-0.1.18/razf.o: In function `razf_close':
razf.c:(.text+0x263e): undefined reference to `inflateEnd'
razf.c:(.text+0x26a0): undefined reference to `deflate'
razf.c:(.text+0x26bd): undefined reference to `deflateEnd'
razf.c:(.text+0x28ed): undefined reference to `deflate'
collect2: error: ld returned 1 exit status
Makefile:87: recipe for target 'SOAP3-DP' failed
make: *** [SOAP3-DP] Error 1
`

**Comment by aquaskyline** [comment]
you should have libz installed.
