### ISSUE TITLE
hardware problem

### ISSUE THREAD

**Issue by descostesn** [aquaskyline/SOAP3-dp#6]
Hi,

I see that your tool is using cuda 4, is it possible to update it to a more recent one?

I cannot use it currently.

Thanks.

**Comment by chunlaw** [comment]
The commit [#3011f30](https://github.com/aquaskyline/SOAP3-dp/commit/3011f3069fb0e2e58ad1f1a309bb3bf85db5934a) maximise GPU compatibility with CUDA 11.

Please check out the commit log file and change the -arch flag in Makefile to boost the performance for your target GPU.
